name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.10, 3.11, 3.12]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi
        pip install pytest pytest-cov pytest-asyncio
        pip install -e .
    - name: Test with pytest
      run: |
        pytest tests/ --cov=a2a_adapter
    - name: Verify A2A compatibility
      run: |
        # Start server in background
        python -m a2a_adapter.cli serve examples/crewai_catalog.py --host 127.0.0.1 --port 8080 &
        SERVER_PID=$!
        
        # Wait for server to start
        sleep 3
        
        # Run compliance test
        python examples/test_compliance.py
        
        # Kill server
        kill $SERVER_PID